!jmb-configuration-v1

name: JMB1
outboundEndpoints:
- name: STR
  flow:
    name: jmsOutboundFlow
    parameters:
    - name: "queue"
      value: "MB-STR"
- name: PALLETESTIMATOR-Q
  flow:
    name: jmsOutboundFlow
    parameters:
    - name: "queue"
      value: "MB-PALLETESTIMATOR"
- name: HOST
  flow:
    name: jmsOutboundFlow
    parameters:
    - name: "queue"
      value: "MB-HOST"
- name: TMA
  flow:
    name: jmsOutboundFlow
    parameters:
    - name: "queue"
      value: "MB-TMA"
- name: WMAENVB
  flow:
    name: jmsOutboundFlow
    parameters:
    - name: "queue"
      value: "MB-WMAENVB"
- name: WMAENVG
  flow:
    name: jmsOutboundFlow
    parameters:
    - name: "queue"
      value: "MB-WMAENVG"
- name: ACK
  flow:
    name: jmsOutboundFlow
    parameters:
    - name: "queue"
      value: "MB-ACK"
- name: OMS
  flow:
    name: jmsOutboundFlow
    parameters:
    - name: "queue"
      value: "MB-OMS"
outboundMappings:
  - receiver: 'HOST.GLOBAL'
    request: '*:*:*'
    outboundEndpoint: 'HOST'
  - receiver: 'TMS.GLOBAL'
    request: '*:*:*'
    outboundEndpoint: 'TMA'
  - receiver: 'LOC.DC0001'
    request: '*:*:*'
    outboundEndpoint: 'WMAENVB'   
  - receiver: 'LOC.DC0002'
    request: '*:*:*'
    outboundEndpoint: 'WMAENVB'
  - receiver: 'LOC.DC1001'
    request: '*:*:*'
    outboundEndpoint: 'WMAENVG'
  - receiver: 'LOC.DC1002'
    request: '*:*:*'
    outboundEndpoint: 'WMAENVG'
  - receiver: 'ACK.GLOBAL'
    request: '*:*:*'
    outboundEndpoint: 'ACK'
